name: Lev

audio:
  driver: coreaudio
  device: BlackHole16ch_UID

server:
  jacktrip_url: 127.0.0.1:4464
  messaging_url: 127.0.0.1:8000

ports:
  receive:
    # local_source_idx: remote_destination_idx
    1: 1

  send:
    # local_destination_idx: remote_source_idx
    3: 2
