name: Lev

audio:
  driver: coreaudio
  device: BlackHole16ch_UID

server:
  jacktrip_port: 4464
  messaging_port: 8000
  host: 127.0.0.1

ports:
  receive:
    # local_source_idx: remote_destination_idx
    1: 1
    2: 2
    3: 3

  send:
    # local_destination_idx: remote_source_idx
    4: 4
    5: 5
