# Sender           |       network       |  Receiver
# capture -> send  |||||||||||||||||||||||  receive -> playback
# It doesn't matter whether server is sender or receiver and vice versa with the client.

server:
  address: 10.0.1.2
  port: 4464
  backend: coreaudio
  device: BlackHole16ch_UID
  channels:
    # TODO: Channel connector doesn't detect local ports because its registration happends when JACK server starts.
    # system:capture_1: Ivan:send_1
    # system:capture_2: Ivan:send_2
    # system:capture_3: Ivan:send_3
    # system:capture_4: Ivan:send_4
    # system:capture_5: Ivan:send_5
    # system:capture_6: Ivan:send_6
    # system:capture_7: Ivan:send_7
    # system:capture_8: Ivan:send_8
    # system:capture_9: Ivan:send_9
    # system:capture_10: Ivan:send_10
    # system:capture_11: Ivan:send_11
    # system:capture_12: Ivan:send_12
    # system:capture_13: Ivan:send_13
    # system:capture_14: Ivan:send_14
    # system:capture_15: Ivan:send_15
    # system:capture_16: Ivan:send_16
    # Ivan:receive_1: system:playback_1
    system:capture_1: system:playback_1

client:
  remote_name: Ivan
  port: 4464
  backend: coreaudio
  device: BlackHole16ch_UID
  channels:
    # JackTrip:receive_1: system:playback_1
    # JackTrip:receive_2: system:playback_2
    # JackTrip:receive_3: system:playback_3
    # JackTrip:receive_4: system:playback_4
    # JackTrip:receive_5: system:playback_5
    # JackTrip:receive_6: system:playback_6
    # JackTrip:receive_7: system:playback_7
    # JackTrip:receive_8: system:playback_8
    # JackTrip:receive_9: system:playback_9
    # JackTrip:receive_10: system:playback_10
    # JackTrip:receive_11: system:playback_11
    # JackTrip:receive_12: system:playback_12
    # JackTrip:receive_13: system:playback_13
    # JackTrip:receive_14: system:playback_14
    # JackTrip:receive_15: system:playback_15
    # JackTrip:receive_16: system:playback_16
    system:capture_1: JackTrip:send_1
